version: 2.1
jobs:
  test:
    docker:
      - image: kyotsuya/wai-middleware-validation-test:lts-16.31
    steps:
      - checkout
      - run: stack test
workflows:
  version: 2
  push:
    jobs:
      - test:
          filters:
            branches:
              ignore: gh-pages
